// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('c:/Users/joaor/OneDrive/Área de Trabalho/Faculdade/Projeto APP/pdm_aulas_2023_1/node_modules/react');
var { Component } = React;
var ReactNative = require('c:/Users/joaor/OneDrive/Área de Trabalho/Faculdade/Projeto APP/pdm_aulas_2023_1/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('pdm_aulas_2023_1', appParameters);
});
require('c:/Users/joaor/OneDrive/Área de Trabalho/Faculdade/Projeto APP/pdm_aulas_2023_1/index.js');